---
name: Build and Deploy coreQ's site to Github Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:   
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
 
    - name: Install npm packages
      run: npm ci

    - name: Build
      run: npm run build


      # - name: Test
      #   run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'ujjwalnp'
        git config --global user.email 'dhakalujjwal99@gmail.com'
        git remote set-url origin http://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        npm run deploy